### ISSUE TITLE
Send pull requests to the Capstone

### ISSUE THREAD

**Issue by XVilka** [Phosphorus15/Capstone#11]
- https://github.com/rizinorg/capstone
- https://github.com/capstone-engine/capstone

**Comment by Phosphorus15** [comment]
Hi! I'd say we're ready for starting a pull request @XVilka, how could I open pr for this repository (since it is not considered by GitHub a fork of rizinorg/capstone or capstone-engine/capstone)?

**Comment by XVilka** [comment]
You have to make a forks of those and add your changes there. I think
GitHub doesn't allow to do PRs of the unrelated repositories.
